### PR TITLE
Update README.md to add an FAQ item about Sequel Pro and MySQL 8

### PR DESCRIPTION
**Pull request by ian-nisbet**
I had trouble with SequelPro when I first started using Takeout.

### CODE REVIEW

**Comment by josecanhelp** [comment]
@ian-nisbet I am able to replicate connection issues with sequel pro when using mysql 8. But mysql 5.7 works fine.

When attempting to connect with sequel pro using mysql 8, using `0.0.0.0` did not help. This is likely an issue with how sequel pro is connecting to mysql 8 and it isn't really something we can fix on our end.

Can you help me verify that this is the case? If so, maybe we can add a warning in the README about this specific situation.

**Comment by mattstauffer** [comment]
@josecanhelp OK, so @ian-nisbet is saying switching to `0.0.0.0` helped but you're saying it didn't? Just want to make sure--thanks!

**Comment by josecanhelp** [comment]
@mattstauffer I just attempted to reproduce this again. I was able to connect with Sequel Pro using `127.0.0.1` without any issue. Unfortunately, Sequel Pro hasn't had a release since 2016 so it is known to be finicky.

image

**Comment by josecanhelp** [comment]
@ian-nisbet I am going to close this ticket out. Sequel Pro should likely be avoided as a client. Per Freek, there is a more updated version called [Sequel Ace](https://sequel-ace.com/).

https://twitter.com/freekmurze/status/1301030834879770625

**Pull request closed without merging**
