### PR TITLE
Add MailHog Service

### PR DESCRIPTION
**Pull request by r2luna**
It installs [MailHog](https://github.com/mailhog/MailHog)

Using [Valet Proxy](https://laravel.com/docs/master/valet#proxying-services) you can add a custom domain to MailHog.

```
valet proxy mailhog http://127.0.0.1:8025
```

Now you can use http://mailhog.test

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks @r2luna!

**Comment by mattstauffer** [comment]
@r2luna I see that you didn't add a volume; does that mean Mailhog's Docker doesn't need a volume for any reason?

**Comment by mattstauffer** [comment]
@r2luna Also--using 1025 as the default port.. that port is occupied on my Mac and I've never set this up with anything in particular. Is 1025 actually going to work for most people?

**Comment by mattstauffer** [comment]
@josecanhelp Showed me 1025 is the right default:

image

So we'll just allow it to stay that way.

Looks like this is what's occupying mine, in case anyone else has this issue:

https://apple.stackexchange.com/questions/356622/what-is-identityservicesd

**Comment by r2luna** [comment]
Great. I was about to send you that. About the volume, I'll send you another PR with the configuration for that.

**Pull request merged**
